donacion = float(input("Ingrese donación: "))
Mgeneral = (donacion * 0.45)
cardiologia = (donacion * 0.30) 
pediatria = (donacion * 0.15) 
traumatologia = (donacion - pediatria - Mgeneral - cardiologia)
print ("Para medicina general es: ", Mgeneral)
print ("Para cardiologia es: ", cardiologia)
print ("Para pediatria es: ", pediatria)
print ("Para traumatologia es: ", traumatologia)
suma = (Mgeneral + cardiologia + pediatria + traumatologia)
print (suma)
