-- MySQL Script generated by MySQL Workbench
-- Wed May 27 13:18:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dom-t
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dom-t
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dom-t` DEFAULT CHARACTER SET utf8 ;
USE `dom-t` ;

-- -----------------------------------------------------
-- Table `dom-t`.`categoriaAlmacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`categoriaAlmacen` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`subCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`subCategoria` (
  `idsubCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `categoriaAlmacen_idtable1` INT NULL,
  PRIMARY KEY (`idsubCategoria`),
  INDEX `fk_subCategoria_categoriaAlmacen1_idx` (`categoriaAlmacen_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_subCategoria_categoriaAlmacen1`
    FOREIGN KEY (`categoriaAlmacen_idtable1`)
    REFERENCES `dom-t`.`categoriaAlmacen` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`almacen` (
  `idalmacen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` TEXT NOT NULL,
  `categoriaAlmacen_idtable1` INT NULL,
  `subCategoria_idsubCategoria` INT NULL,
  PRIMARY KEY (`idalmacen`),
  INDEX `fk_almacen_categoriaAlmacen1_idx` (`categoriaAlmacen_idtable1` ASC) VISIBLE,
  INDEX `fk_almacen_subCategoria1_idx` (`subCategoria_idsubCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_almacen_categoriaAlmacen1`
    FOREIGN KEY (`categoriaAlmacen_idtable1`)
    REFERENCES `dom-t`.`categoriaAlmacen` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almacen_subCategoria1`
    FOREIGN KEY (`subCategoria_idsubCategoria`)
    REFERENCES `dom-t`.`subCategoria` (`idsubCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`logo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`logo` (
  `idlogo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `logo` MEDIUMBLOB NOT NULL,
  `almacen_idalmacen` INT NULL,
  PRIMARY KEY (`idlogo`),
  INDEX `fk_logo_almacen1_idx` (`almacen_idalmacen` ASC) VISIBLE,
  CONSTRAINT `fk_logo_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `dom-t`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`talla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`talla` (
  `idtalla` INT NOT NULL AUTO_INCREMENT,
  `talla` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtalla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`categoriaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`categoriaProducto` (
  `idcategoriaProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoriaProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `detalle` TEXT NOT NULL,
  `almacen_idalmacen` INT NULL,
  `talla_idtalla` INT NULL,
  `categoriaProducto_idcategoriaProducto` INT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_almacen1_idx` (`almacen_idalmacen` ASC) VISIBLE,
  INDEX `fk_producto_talla1_idx` (`talla_idtalla` ASC) VISIBLE,
  INDEX `fk_producto_categoriaProducto1_idx` (`categoriaProducto_idcategoriaProducto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `dom-t`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_talla1`
    FOREIGN KEY (`talla_idtalla`)
    REFERENCES `dom-t`.`talla` (`idtalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_categoriaProducto1`
    FOREIGN KEY (`categoriaProducto_idcategoriaProducto`)
    REFERENCES `dom-t`.`categoriaProducto` (`idcategoriaProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`imagenesProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`imagenesProducto` (
  `idimagenesProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` MEDIUMBLOB NOT NULL,
  `producto_idproducto` INT NULL,
  PRIMARY KEY (`idimagenesProducto`),
  INDEX `fk_imagenesProducto_producto_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_imagenesProducto_producto`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `dom-t`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `usuaio` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `almacen_idalmacen` INT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_almacen1_idx` (`almacen_idalmacen` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `dom-t`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`gerente` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `almacen_idalmacen` INT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_gerente_almacen1_idx` (`almacen_idalmacen` ASC) VISIBLE,
  CONSTRAINT `fk_gerente_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `dom-t`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dom-t`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dom-t`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario_idusuario` INT NULL,
  `almacen_idalmacen` INT NULL,
  `producto_idproducto` INT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_pedido_almacen1_idx` (`almacen_idalmacen` ASC) VISIBLE,
  INDEX `fk_pedido_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `dom-t`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `dom-t`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `dom-t`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
